### ISSUE TITLE
Remove ProximaNova font call from theme.css

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/jekyll-example#3]
Remove ProximaNova from theme.css, to avoid abundant errors in the Docker console (and since the font doesn't seem to be needed). I think this would do the job:
```
perl -pi -e 's/ProximaNova,//' theme.css
perl -pi -e 's{^(.font-face.+)}{/* $1 */}' theme.css
```
Relatedly: I'd like to get guidance (@alancleary @nathanweeks) about how to handle changes in the theme submodule (legumeinfo-jekyll-theme). Initiate a separate PR to that repo? Or: point to a particular commit for changes to the submodule?

**Comment by alancleary** [comment]
Can you confirm that these are the lines causing the errors: https://github.com/legumeinfo/legumeinfo-jekyll-theme/blob/dlt-jekyll-theme/assets/css/theme.css#L5451-L5455. Proxima Nova is a proprietary font, so if we want to actually serve the files these lines are referring to then we'll have to pay.

Personally, I think using a proprietary font is somewhat antithetical to the LIS open-source philosophy. However, macOS does come with the different flavors of Proxima Nova used in the theme. So if you simply remove the lines that say we're providing the font files then the user's browser should acquire the font from their system, or fall back to one of the other fonts specified if their system doesn't have it.

Admittedly, I took the theme from the UIkit [documentation site](https://getuikit.com/docs/introduction) (code: https://github.com/uikit/uikit-site), so I'm not particularly wed to the fonts specified. However, I used the theme because of its aesthetics so I think preserving the fonts specified to the extent we can is worth doing, i.e. using Proxima Nova if it's on the user's system.

At some point I think we should have a discussion about the theme. Do we want to stick with it or craft our own? Do we want the vertical "Tools" menu to be on every page?

Regarding how to handle changes in the theme submodule, I'll have to look into it since this is my first time developing with a submodule. My guess would be yes, you would have to initiate a separate pull request and then have your pull request over here update the SHA1 commit the submodule refers to over here, which appears to actually be the case in your most recent pull request.

**Comment by cann0010** [comment]
If Proxima Nova is proprietary, that's all the more reason to remove it from the CSS. If it's proprietary, and isn't available on Mac by default, I don't think we should develop around it. The errors in the Docker console did go away after I removed the lines you indicated, along with the ones that begin "font-family: ProximaNova,". 

The theme: I don't mind the one we're using - though there are lots of little things that I'd prefer to tweak: spacing around header text, etc. I don't know at what point this becomes "crafting our own." Also, I have made very little explicit use of the CSS. I'll need help from someone with more html/css expertise to make stuff look better. For example, on the current genus pages, it would be nice to make better use of space around the images - and maybe to put the longer descriptive text in a collapsible div.

As for the vertical Tools menu: I mostly like it, but it would be nice to have another page template (as an option) that doesn't have that menu. I am pretty sure there will be some pages or I-frame'd apps for which we'll want to maximize real estate.

**Comment by alancleary** [comment]
> If it's proprietary, and isn't available on Mac by default, I don't think we should develop around it

It is available on macOS, which is why I think we should keep it so mac users can experience the theme as the designers intended. We can just remove the lines that say we're providing the font files for it.

> The errors in the Docker console did go away after I removed the lines you indicated, along with the text "ProximaNova," from the lines ones that begin "font-family: ProximaNova,".

Did you try leaving "ProximaNova" in the lines that begin with "font-family: ProximaNova" and removing the lines that say we're providing the font files? The browser should gracefully fallback to the other fonts in these lines if it can't find ProximaNova on the user's system.

> The theme: I don't mind the one we're using - though there are lots of little things that I'd prefer to tweak

We should discuss this some time so I can determine what's coming from the theme and what's coming from the framework.

> As for the vertical Tools menu: I mostly like it, but it would be nice to have another page template (as an option) that doesn't have that menu. I am pretty sure there will be some pages or I-frame'd apps for which we'll want to maximize real estate.

Open an issue for this and I'll make it so.

**Comment by cann0010** [comment]
"It is available on macOS" -- Ah, I see them now. We just weren't pointing to them.
"We can just remove the lines that say we're providing the font files for it." -- OK.
"Did you try ... [just] removing the lines that say we're providing the font files?" -- Trying that now: you're right. That is sufficient. I am not seeing the errors now.
